app/books/api/urls.py
# from django.urls import path
from rest_framework.routers import DefaultRouter
from books.api import views

app_name = 'books-api'

# urlpatterns = [
#     path('api/v1/books/', BookList.as_view()),
#     path('api/v1/books/<int:pk>/', BookInstanceView.as_view())
# ]


router = DefaultRouter()
router.register(r'books', views.BookModelViewSet, basename='book')
router.register(r'authors', views.AuthorModelViewSet, basename='author')
router.register(r'categories', views.CategoryModelViewSet, basename='category')
urlpatterns = router.urls

app/books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('create/', views.BookCreate.as_view(), name='create'),
    path('viewing/<int:pk>/', views.BookViewing.as_view(), name='book-viewing'),
    path('list/', views.BookList.as_view(), name='list'),
    path('list/my-books/', views.MyBooksList.as_view(), name='my-books'),
    path('list/my-requested-books/', views.MyRequestedBooks.as_view(), name='my-requested-books'),
    path('list/requested-books/', views.RequestedBooks.as_view(), name='requested-books'),
    path('requested-books/confirm/<int:request_id>/', views.RequestBookConfirm.as_view(),
         name='requested-books-confirm'),
    path('requested-books/reject/<int:request_id>/', views.RequestBookReject.as_view(),
         name='requested-books-reject'),
    path('requested-books/sent-via-email/<int:request_id>/', views.RequestBookSentViaEmail.as_view(),
         name='sent-via-email'),
    path('requested-books/book-received/<int:request_id>/', views.RequestBookReceivedBook.as_view(),
         name='book-received'),
    path('requested-books/sent-back-to-owner/<int:request_id>/', views.RequestBookSentBackToOwner.as_view(),
         name='sent-back-to-owner'),
    path('requested-books/owner-received/<int:request_id>/', views.RequestBookOwnerReceivedBack.as_view(),
         name='owner-received'),
    path('create/book/request/<int:book_id>/', views.RequestBookCreate.as_view(), name='create-book-request'),
    path('list/my-authors/', views.MyAuthorsList.as_view(), name='my-authors'),
    path('authors/create/', views.AuthorCreate.as_view(), name='authors-create'),
    path('authors/list/', views.AuthorList.as_view(), name='authors-list'),
    path('update/<int:pk>/', views.BookUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.BookDelete.as_view(), name='delete'),
    path('download-csv/', views.DownloadCSVBookView.as_view(), name='download-csv'),
    path('download-xlsx/', views.DownloadXLSXBookView.as_view(), name='download-xlsx'),
    path('authors/download-csv/', views.DownloadCSVAuthorView.as_view(), name='authors-download-csv'),
    path('authors/download-xlsx/', views.DownloadXLSXAuthorView.as_view(), name='authors-download-xlsx'),
    path('authors/update/<int:pk>/', views.AuthorUpdate.as_view(), name='authors-update'),
    path('authors/delete/<int:pk>/', views.AuthorDelete.as_view(), name='authors-delete'),
]

app/booksharing/urls.py
import debug_toolbar
from django.urls import include, path, re_path
from django.contrib import admin
from books import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import MyProfileView, ContactUsView, SignUpView, ActivateView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

API_V1_PREFIX = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.Index.as_view(), name='index'),
    path('__debug__/', include(debug_toolbar.urls)),

    path('accounts/my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('accounts/contact-us/', ContactUsView.as_view(), name='contact-us'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/activate/<uuid:username>/<token>/', ActivateView.as_view(), name='activate'),

    path('books/', include('books.urls')),
    path(API_V1_PREFIX, include('books.api.urls')),

    path('logs/', views.LogList.as_view(), name='logs'),

    path(f'{API_V1_PREFIX}token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_V1_PREFIX}token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns += [
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

app/books/models.py
from django.db import models
from books import model_choices as mch


def book_upload_cover(instance, filename):
    path = f'covers/{instance.user.id}/{filename}'
    return path


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    date_of_birth = models.CharField(max_length=64)
    date_of_death = models.CharField(max_length=64)
    country = models.CharField(max_length=128)
    gender = models.CharField(max_length=32)
    language = models.CharField(max_length=64)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE,
                             null=True, default=None)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Book(models.Model):
    cover = models.FileField(null=True, default=None, upload_to=book_upload_cover)
    title = models.CharField(max_length=128)
    publish_year = models.PositiveIntegerField()
    review = models.CharField(max_length=512)
    condition = models.PositiveSmallIntegerField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, default=None)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE,
                             null=True, default=None)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL,
                               null=True, default=None)


class Log(models.Model):
    path = models.CharField(max_length=500)
    method = models.CharField(max_length=32)
    time = models.PositiveIntegerField()


class RequestBook(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    recipient = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    status = models.PositiveSmallIntegerField(choices=mch.REQUEST_STATUSES)

app/books/forms.py
from django import forms

from books.models import Book, Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'cover',
            'author',
            'title',
            'category',
            'publish_year',
            'review',
            'condition'
        )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user

        if commit:
            instance.save()

        return instance


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = (
            'first_name',
            'last_name',
            'date_of_birth',
            'date_of_death',
            'country',
            'gender',
            'language'
        )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user

        if commit:
            instance.save()

        return instance

app/books/api/views.py
from rest_framework import viewsets, filters
from books.models import Book, Author, Category
from books.api.serializers import BookSerializer, AuthorSerializer, CategorySerializer
from books.api.filters import BookFilter, AuthorFilter, CategoryFilter
from django_filters.rest_framework import DjangoFilterBackend


# class BookList(generics.ListCreateAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer
#
#
# class BookInstanceView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Book.objects.all()
#     serializer_class = BookSerializer


class BookModelViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    ordering_fields = ['condition']
    # filterset_fields = ['condition']
    filterset_class = BookFilter


class AuthorModelViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    ordering_fields = ['last_name']
    filterset_class = AuthorFilter


class CategoryModelViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    ordering_fields = ['name']
    filterset_class = CategoryFilter

app/books/templates/books/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}


<h1>Do you really want to delete author with id: {{ object.pk }}?</h1>

<form method="post">{% csrf_token %}
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

app/books/templates/books/author_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>{{ message }}</h1>

<p>Form to create a author</p>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>

{% if form.instance.id %}
    <a href="{% url 'books:authors-delete' form.instance.id %}">DELETE</a>
{% endif %}

{% endblock content %}

app/books/templates/books/author_list.html
{% extends 'base.html' %}

{% block content %}

    <a href="{% url 'books:authors-download-csv' %}">Download CSV</a> <br>
    <a href="{% url 'books:authors-download-xlsx' %}">Download XLSX</a> <br>

    <table border="1">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date of Birth</th>
            <th>Date of Death</th>
            <th>Country</th>
            <th>Gender</th>
            <th>Language</th>
        </tr>

        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.id }}</td>
                <td>{{ object.first_name }}</td>
                <td>{{ object.last_name }}</td>
                <td>{{ object.date_of_birth }}</td>
                <td>{{ object.date_of_death }}</td>
                <td>{{ object.country }}</td>
                <td>{{ object.gender }}</td>
                <td>{{ object.language }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock content %}

app/books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}


<h1>Do you really want to delete book with id: {{ object.pk }}?</h1>

<form method="post">{% csrf_token %}
    <input type="submit" value="Confirm">
</form>

{% endblock content %}

app/books/templates/books/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>{{ message }}</h1>

<p>Form to create a book</p>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>


{% if form.instance.id %}
    <a href="{% url 'books:delete' form.instance.id %}">DELETE</a>
{% endif %}


{% endblock content %}

app/books/templates/books/book_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col">
            <a class="btn btn-success" href="{% url 'books:download-csv' %}">Download CSV</a>
            <a class="btn btn-success" href="{% url 'books:download-xlsx' %}">Download XLSX</a>
            <table class="table table-striped font-size-12">
                <tr>
                    <th>#</th>
                    <th>ID</th>
                    <th>Author Name</th>
                    <th>Title</th>
                    <th>Publish Year</th>
                    <th>Review</th>
                    <th>Condition</th>
                    <th></th>
                </tr>

                {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a class="btn btn-primary" href="{% url 'books:book-viewing' object.id %}">{{ object.id }}</a></td>
                        <td>
                            {{ object.author.first_name }}
                            {{ object.author.last_name }}
                        </td>
                        <td>{{ object.title }}</td>
                        <td>{{ object.publish_year }}</td>
                        <td>{{ object.review }}</td>
                        <td>{{ object.condition }}</td>
                        <td><a class="btn btn-primary" href="{% url 'books:create-book-request' object.id %}">Request Book</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock content %}

app/books/templates/books/book_viewing.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-2"><img class="w-100 h-100" src="{% if object.cover %} {{ object.cover.url }} {% endif %}" alt="Book Cover"></div>
        <div class="col-10">
            <h4 class="text-primary"><span>Title:</span> {{ object.title }}</h4>
            <h4 class="text-primary"><span>Author:</span> {{ object.author }}</h4>
            <h4 class="text-primary"><span>Category:</span> {{ object.category }}</h4>
            <h4 class="text-primary"><span>Publish year:</span> {{ object.publish_year }}</h4>
            <h4 class="text-primary"><span>Review:</span> {{ object.review }}</h4>
        </div>
    </div>
</div>



{% endblock content %}

app/books/templates/books/log_list.html
{% extends 'base.html' %}

{% block content %}

{% for log in object_list %}
    PATH: {{ log.path }} <br> METHOD: {{ log.method }} <br> TIME: {{ log.time }} <br> <br>
{% endfor %}


{% endblock content %}

app/books/templates/books/my_authors.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'books:authors-create' %}">authors create</a>

    <br>

    <table border="1">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Date Of Birth</th>
            <th>Date Of Death</th>
            <th>Country</th>
            <th>Gender</th>
            <th>Language</th>
            <th></th>
        </tr>

        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.id }}</td>
                <td>{{ object.first_name }}</td>
                <td>{{ object.last_name }}</td>
                <td>{{ object.date_of_birth }}</td>
                <td>{{ object.date_of_death }}</td>
                <td>{{ object.country }}</td>
                <td>{{ object.gender }}</td>
                <td>{{ object.language }}</td>
                <td><a href="{% url 'books:authors-update' object.pk %}">
                    Edit</a></td>
            </tr>
        {% endfor %}
    </table>

<h1>{{ object }}</h1>

{% endblock content %}

app/books/templates/books/my_books.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'books:create' %}">books create</a>

    <br>

    <table border="1">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Author Name</th>
            <th>Title</th>
            <th>Category</th>
            <th>Publish Year</th>
            <th>Review</th>
            <th>Condition</th>
            <th></th>
        </tr>

        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.id }}</td>
                <td>
                    {{ object.author.first_name }}
                    {{ object.author.last_name }}
                </td>
                <td>{{ object.title }}</td>
                <td>{{ object.category.name }}</td>
                <td>{{ object.publish_year }}</td>
                <td>{{ object.review }}</td>
                <td>{{ object.condition }}</td>
                <td><a href="{% url 'books:update' object.pk %}">
                    Edit</a></td>
            </tr>
        {% endfor %}
    </table>

<h1>{{ object }}</h1>

{% endblock content %}

app/books/templates/books/requestbook_list.html
{% extends 'base.html' %}

{% block content %}

    <table border="1" style="color: red;">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Book</th>
            <th>Created</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>

        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.id }}</td>
                <td>{{ object.book.title }}</td>
                <td>{{ object.created }}</td>
                <td>{{ object.get_status_display }}</td>
                <td>
                    {% if object.status == mch.STATUS_SENT_TO_RECIPIENT %}
                        <a href="{% url 'books:book-received' object.id %}">
                            I got the book!</a>
                    {% elif object.status == mch.STATUS_RECIPIENT_RECEIVED_BOOK %}
                        <a href="{% url 'books:sent-back-to-owner' object.id %}">
                            Sent back to owner</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock content %}

app/books/templates/books/requested_book_list.html
{% extends 'base.html' %}

{% block content %}

    <table border="1" style="color: blue;">
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>Book</th>
            <th>Created</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>

        {% for object in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ object.id }}</td>
                <td>{{ object.book.title }}</td>
                <td>{{ object.created }}</td>
                <td>{{ object.get_status_display }}</td>
                <td>
                    {% if object.status == mch.STATUS_IN_PROGRESS %}
                        <a href="{% url 'books:requested-books-confirm' object.id %}">Confirm</a> |
                        <a href="{% url 'books:requested-books-reject' object.id %}">Reject</a>
                    {% elif object.status == mch.STATUS_CONFIRMED %}
                        <a href="{% url 'books:sent-via-email' object.id %}">Sent Via Email</a>
                    {% elif object.status == mch.STATUS_REJECT %}
                        <p>The book was Rejected by owner!</p>
                    {% elif object.status == mch.STATUS_SENT_BACK_TO_OWNER %}
                        <a href="{% url 'books:owner-received' object.id %}">I received book back!</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock content %}